### ISSUE TITLE
Проекты в GitHub должны называться как проекты, например, distance-calculator

### ISSUE THREAD

**Issue by coursar** [AIRAT1/Task1#2]

**Comment by coursar** [comment]
Это на будущее. Если поменяете название этого, нужно будет сделать:
```
git remote remove origin
git remote add origin ... <url вашего нового репо>
```

**Comment by AIRAT1** [comment]
поменял имя проекта на гитхабе. Потом в идее ctrl + T. Сделал изменения по замечаниям и закоммитил и запушил их на сервер. Дальше в гитбаше 
git remote
git remote remove origin
git remote add origin https://github.com/AIRAT1/distance-calculator
